### ISSUE TITLE
Scroll reverser preferences randomly change. 

### ISSUE THREAD

**Issue by lynndixon** [pilotmoon/Scroll-Reverser#38]
I am on Sierra, 10.12.1.  Using Scroll Reverser 1.7.4. 
I usually keep the "reverse trackpad" and "reverse tablet" settings unchecked, as I don't want my trackpad reversed.  

But seemingly randomly. I will notice my trackpad scrolling will start reversing, without me doing anything.  Literally scrolling fine on webpages, then click something, then scrolling will be reversed.

When I go to the Scroll Reverser settings, I notice that my preferences for "Reverse Trackpad" and "reverse tablet" have been selected.   
Oddly enough, if I click either one of them to un-check them, the other will automatically go unchecked.

This happens several times per day.

**Comment by invariant** [comment]
Is it possible you have an older copy of Scroll Reverser running at the same time? Two copies running at once could explain this (both trying to use the same preference file).

**Comment by invariant** [comment]
Ref: **[Conversation #5351](https://secure.helpscout.net/conversation/286689157/5351) / Phoebus**

**Comment by lynndixon** [comment]
I have verified I am not running two instances or an older copy alongside a newer one.  I completely removed all occurrences of Scroll Reverser from my Mac, rebooted, and installed only the newest version, but I am still seeing these odd problems.

**Comment by invariant** [comment]
Thank you for your help eliminating this hypothesis.

**Comment by invariant** [comment]
As an general position on this issue - I have had a look over the code and I cannot see any reason for this to be happening. It does not happen in my own testing. If anyone reading is able to suggest the cause, or a fix, I'm all ears.

**Comment by invariant** [comment]
Ref: **[Conversation #5396](https://secure.helpscout.net/conversation/294909729/5396) / Steffen**

**Comment by akhilcb** [comment]
Thanks for this awesome app. I wanted to report the same issue. I have the exact issue as mentioned above on Sierra, 10.12.2, using Scroll Reverser 1.7.4. This just happened with me when I opened Chrome browser and suddenly the scroll direction reversed. This has happened many times in the past. I used to go to preferences and uncheck again when that happens. Is there someway to make the preferences read-only or something so that it cant automatically revert it? Or did anyone find any work around?

**Comment by yuezhu** [comment]
I would like to appreciate you for this great app first. I wanted to report the same problem on my 15 inch Mid 2012 MacBook Pro, which is running macOS Sierra. Any log files I can provide to help you debug?

**Comment by SystemDisc** [comment]
If I set my preferences, close the app, and open it, the preferences are as I set them. If I set my preferences, restart my computer, or logout, then login, my preferences are set to the defaults.

I would like Reverse Trackpad and Reverse Tablet unchecked, and Reverse Mouse checked, so that mouses work the way they're supposed to.

<img src="https://i.imgur.com/RiGBU3l.png">

**Comment by SystemDisc** [comment]
My apologies. It is not nearly this consistent. After writing this post, to make sure I wasn't lying, I logged out and back in. My preferences were as I set them. I then restarted, and my preferences were still as I set them. So, I guess I'm in the same boat as everyone else. At some point, I do not know what triggers it, my preferences get reset to default and the next time the app is opened, the preferences are in their default states.

**Comment by kingo55** [comment]
I haven't got any scientific measurements but I feel like this happens every 12-24hrs.

I wonder if there's a scheduled job running that affects the settings?

**Comment by ashour** [comment]
+1 on this. Getting it at regular internals. I'm on Scroll Reverser 1.7.4, macOS Sierra 10.12.3.

**Comment by bu-ra3y** [comment]
+1
Settings reset to something like a default every so often (every day or two)?

**Comment by kingo55** [comment]
Yes, it started happening much more regularly for me all of a sudden too.

Possibly following some Mac OS update not too long ago.

**Comment by akhilcb** [comment]
This is happening very frequently now. Everyday once or twice I am facing this issue. Suddenly the scroll direction reverses. I am having v1.7.5 on Sierra 10.12.5. Anyone found anyway to modify this default preference selection to something of ours so that even when it is resetting, it will still have the same selection. Any hacks? like replacing some plist file with a modified one inside app?

**Comment by invariant** [comment]
I released Scroll Reverser 1.7.6 today, which has some changes to preferences handling. At the moment I am unable to reproduce this bug myself, so this is NOT a fix. But it is possible my changes have had some effect. Please let me know if you observe any differences after upgrading to 1.7.6.

**Comment by Cyb3rfr3ak** [comment]
Seems like it is still happening (macOS 10.12.4, Scroll Reverser 1.7.6)

**Comment by invariant** [comment]
Thank you @Cyb3rfr3ak. I have had other reports too.

At this point I have no clue why this is happening. I have gone over every line of code related to preferences, it is all totally standard just like I do it in all my other apps. NSUserDefaults + Cocoa bindings. If anyone can take a look at the code, please do.

For those getting this problem, is it only Scroll Reverser that it happens to or have you seen it with any other apps? Could this be macOS bug?

**Comment by danblakemore** [comment]
I'm also seeing this bug still with 1.7.6 on macOS 10.12.4 (16E195).  @invariant, the only thing I've seen like this on Mac is the preferences for custom keyboard shortcuts for Services within the Keyboard preference pane.

I frequently make keyboard shortcuts to run small scripts running with Automator.  The last time I went to make one when I double-clicked to add set the keyboard shortcut, all of my custom shortcuts were erased (unbound, but still listed).  I am not sure that the system uses NSUserDefaults for storage of these kinds of preferences, but it has the same behavior of toggling one setting changing many (as if reloading valid or invalid settings from a different source than when the list was initially rendered).  This behavior is definitely new to macOS with the most recent versions.

At the risk of getting too off-topic, I've also seen a bug on iOS which looks like a problem specifically with NSUserDefaults: many of the apps on my iPhone will suddenly begin launching as if they had never been run before (including built-in apps like Messages).  I'll get apps that I've had for months asking me to allow notifications and showing me tutorials that I've skipped.  To me, it feels like NSUserDefaults for those apps is getting erased or replaced.

So it may be a bug in Foundation as you suspect.

**Comment by CNG** [comment]
Thanks everyone for allowing me to subtract one from list of reasons I might be crazy.

**Comment by mcmccaleb** [comment]
I can't tell if this is the same bug, but I am also running into similar issues on Sierra 10.12.5 with Scroll Reverser v1.7.5. 

In my case, I am only reversing the mouse, but randomly the trackpad will start reversing too. This change does not show up in the preferences, and unchecking and rechecking "Reverse Scrolling" fixes the issue temporarily.
![image](https://cloud.githubusercontent.com/assets/1770214/26747211/269dfb8e-47a9-11e7-84da-fe98853162c6.png)

**Comment by esalter** [comment]
Looks like a lot of others have this issue too, add a +1 from me!

**Comment by esalter** [comment]
I'm in a bit of a unique position because I currently have two laptops, my older one does not exhibit this behavior (that I have seen), the newer one does.  Both are using 1.7.6.  What can I look at to help track down the problem?  The only obvious difference is the older one is set to auto-update but they are on the same version.

Caveat, I will only have the old laptop (where Scroll Reverser works fine) until Wednesday, so let me know soon what you need from me.

**Comment by blairsu** [comment]
First, thank you for this awesome app.

I also encounter the same issue too, the scroll direction randomly changed. (macOS Sierra version 10.12.5).

When this happened, I have to un-check "Reverse Scrolling" and check again to bring it back.

![capture 2017-06-09 at 9 59 23 am](https://user-images.githubusercontent.com/1818299/26957893-5962a58c-4cfa-11e7-866b-2c2b1d34e07c.png)

**Comment by levic** [comment]
To open the preferences window you have to click on the menu bar icon first to make it appear.

Every time I've tested (at least 10 times now), it's simply the action of clicking on the menu bar icon that has made it start working again -- even if I don't choose any of the menu items or open the preferences window.

I thought it might be related to restart-from-sleep, but it's happened to me in the middle of working (no sleep involved). Maybe it be mis-detecting a restart and then not initialising correctly? Unfortunately I've not been able to catch it happening while having the Debug Console open.

**Comment by SystemDisc** [comment]
Are you trying to use scroll reverser in software running as root/admin or with elevated permissions? If so, you need to add Scroll Reverser to the accessibility list for its features to work inside those elevated apps.

**Comment by esalter** [comment]
I have caught this issue happening right in the middle of scrolling. I'll be scrolling a page, normally like I want it, then *in the middle of the scroll* it will reverse direction.  Then I check the settings and they've reverted like others have mentioned in this thread.  So clearly something is actively triggering this to happen; it has nothing to do with restarting or sleeping.

**Comment by tehfink** [comment]
Also just randomly happened to me: trackpad scrolling in Chrome became reversed.
Scroll Reverser: 1.7.6
OS X: 10.12.5
Chrome: 58.0.3029.110

**Comment by akshaypuradkar** [comment]
I'm using synaptics on ubuntu (so i don't use scroll-reverser nor a mac) and i've to manually re-run my synclient script everytime the change mentioned on this thread happens. and it happens absolutely randomly.
it's just bizarre. I'd thought maybe it's the kernel or something because it'd begun only recently, say since four months or so.

**Comment by Nochops** [comment]
I'm running Sierra 10.12.5 on a 2017 MacBook Pro.  Scroll direction changes on its own, and "tap to click" (which is completely uncontrollable) is activated at times.

It doesn't matter if I have Force Click on or off - the same things happen.  It's also seemingly impossible to select filenames in finder without associated apps being opened about half the time.  I've talked to Apple - they have no solutions and these problems have been the same for almost 2 years based on posts in Apple Communities.

**Comment by tiptop103** [comment]
Similar is happening to me and I've noticed that it consistently happens at 11:52 PM every night, and never at any other time. I reset it by disabling/enabling scroll reversing. Hope this helps somewhat.

**Comment by Xanify** [comment]
This has happened to me a couple of times now at 10:55pm. 

I'm running Sierra 10.12.6 (16G29) on a 2017 12" Macbook.

**Comment by lywgit** [comment]
I have this same situation as well. I always set the preference to "reverse Mouse" but not "Trackpad". But occasionally (I think mostly in the middle of using chrome?), the trackpad becomes reversed and I would find "Reverse Trackpad" option checked in the preference panel. 
I am using:

Scroll Reverser: 1.7.6
macOS Sierra 10.12.6 
MacBook Pro 13-inch 2017

This has been a very helpful tool for me,  and hope it can be fixed soon : )

**Comment by weyhmueller** [comment]
I had this behavior before, too.
For some weeks, I am now running macOS High Sierra 10.13 Beta and it never appeared since. I'd  bet your problems will be gone as well when High Sierra is going to be released next month.

**Comment by Mochnant** [comment]
I am also having this issue on OSX 10.12.6.

**Comment by krisscox** [comment]
I'm also having this issue, notice it when waking from sleep sometimes.

Macbook Pro 13" 2016 TB, Sierra 10.12.6

My usual settings are:
[ ] Reverse Trackpad
[✓] Reverse Mouse
[✓] Reverse Tablet

Then it reverts to:
[✓] Reverse Trackpad
[✓] Reverse Mouse
[✓] Reverse Tablet

**Comment by clnhlzmn** [comment]
For what it's worth I too am having this issue. I usually have reverse mouse and tablet selected and not trackpad. Occasionally the preferences will change to all reversed. I'm on Sierra 10.12.6. I haven't detected a pattern or any cause, but I'll try to keep an eye out.

**Comment by Mochnant** [comment]
@invariant Any luck on figuring out what is going on?  Or have we chocked this up to an OSX bug with no fix?  Thanks!

**Comment by invariant** [comment]
I have chalked it up to a OS bug, @Mochnant. I haven't seen any reports of it on 10.13 so far, which is hopeful.

**Comment by KyleKing** [comment]
I have the problem on High Sierra.  My Scroll-Reverser preferences are to only reverse scrolling for the mouse and leave the trackpad as-is; however, sometimes when waking from sleep, the trackpad scroll direction is reversed. Clicking the "Scroll Direction Natural" trackpad setting twice will fix it

**Comment by SystemDisc** [comment]
It seems to happen most frequently for me when waking from sleep, but it does occasionally happen randomly as I'm using my computer normally.

**Comment by invariant** [comment]
@KyleKing When waking from sleep is the preferences setting actually changing, such that the setting has visibly changed in the prefs window (this issue); or is the preference still showing correctly but Scroll Reverser is not obeying it (issue #40)?

**Comment by KyleKing** [comment]
@invariant when waking from sleep all of the preference windows appear correct (`scroll-reverser: only mouse` & `mac trackpad: scroll direction natural is checked`), but the trackpad scroll behavior is reversed. I think my problem may be different because toggling the trackpad setting fixes the issue (https://github.com/pilotmoon/Scroll-Reverser/issues/40#issuecomment-336317973).

I haven't had scroll reverser on for about a week and haven't had any issues, but I can keep scroll-reverser running and post any logs when it happens again.

Probably related: my Launchpad/Desktop multi-finger trackpad gestures keep getting deactivated and become unchecked

**Comment by mcmccaleb** [comment]
@markedelman I think that is an unrelated issue. I had something similar happen in the past and fixed it by changing the "Show scroll bars" setting under System Preferences/General to "When scrolling" instead of "Automatically based on mouse or trackpad"

**Comment by levic** [comment]
> I'd bet your problems will be gone as well when High Sierra is going to be released next month.

Would like to second this; I used to get the bug 2-3 time per week. Since upgrading to High Sierra (a week after release -- around 8 weeks ago now) I haven't had it happen once.

**Comment by iharkh** [comment]
![image](https://user-images.githubusercontent.com/6583990/61296940-d1c0d080-a7e3-11e9-8d01-d5effb1447f2.png)
Allowing the app to monitor inputs helped me with this problem on macOS Catalina.

**Comment by invariant** [comment]
Hi everyone. It looks like most of the action on this issue was from 2017 and I haven't had any recent reports of preferences randomly changing.  I'm going to close the issue now to tidy things up. If you do still have any problems with preference settings not sticing, please report it afresh.

**Comment by nicu-chiciuc** [comment]
EDIT: This is an issue with mackup and the fact that symlinking .plist doesn't work anymore, everything is fine with scroll reverser.

I've been using scroll reverser for multiple years now (thank you very much for the software), but on this new laptop I suddenly started getting these type of issues. When I'd come back to my laptop after awhile (let's say 1-2 hours) I'd see a window with a message "scroll reverser is now running" and the scroll reverser is disabled and the settings are reset.
